### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/RandomPassword#1]
Why all packages have classes?

**Comment by Sid72020123** [comment]
Thanks! All packages have classes to make any number of objects and generate the password!

**Comment by Sid72020123** [comment]
Closing........

**Comment by Sid72020123** [comment]
You can see this video: https://m.youtube.com/watch?v=dEBMGiKC60o

**Comment by Quantum-Codes** [comment]
I NEVER KNEW YOU ARE SO GOOD AT EDITING VIDEOS!!

**Comment by Sid72020123** [comment]
> I NEVER KNEW YOU ARE SO GOOD AT EDITING VIDEOS!!

Thanks!
